[theme]
primaryColor              = "#F0A500"
backgroundColor           = "#EEF2F9"
secondaryBackgroundColor  = "#F0F5FB"
textColor                 = "#0D2137"
font                      = "sans serif"

[server]
maxUploadSize = 10
headless      = true

[browser]
gatherUsageStats = false
